apiVersion: v1
kind: Service
metadata:
  name: zoo
  namespace: kafka
spec:
  ports:
  - port: 9002
    name: peer
  - port: 9002
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
    storage: persistent-regional
